// This file is automatically generated.
// Please do not modify it manually.
declare const styles: {
  readonly themeSwitch: string;
  readonly checked: string;
  readonly track: string;
  readonly clouds: string;
  readonly stars: string;
  readonly slider: string;
  readonly craters: string;
};
export = styles;
export default styles;
